/**
 * @description
 * @export
 * @enum {number}
 */
export enum SupportParams {
    DEFAULT_BOARDS = 'DEFAULT_BOARDS',
    SEND_EMAIL_RECOVER_PASSWORD = 'SEND_EMAIL_RECOVER_PASSWORD',
    RECAPTCHA_PARAMS = 'RECAPTCHA_PARAMS',
    PLAN_FREE = 'PLAN_FREE',
    SEND_EMAIL_COMPLETE_REGISTRY = 'SEND_EMAIL_COMPLETE_REGISTRY',
    EMAIL_SENDER_PARAMS = 'EMAIL_SENDER_PARAMS',
    SEND_EMAIL_CONFFIRMATION = 'SEND_EMAIL_CONFFIRMATION',
    SUPPORT_PARAMS = 'SUPPORT_PARAMS',
    INTEGRATIONS_DEFINITION = "INTEGRATIONS_DEFINITION"
}